-- LinguaLearn Database Schema
-- PostgreSQL (Supabase)
-- This schema is auto-generated by TypeORM synchronize.
-- Provided here for reference and manual setup.

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE IF NOT EXISTS "users" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "email" VARCHAR NOT NULL UNIQUE,
    "username" VARCHAR NOT NULL UNIQUE,
    "passwordHash" VARCHAR NOT NULL,
    "xp" INTEGER DEFAULT 0 NOT NULL,
    "streak" INTEGER DEFAULT 0 NOT NULL,
    "lastActiveDate" DATE,
    "createdAt" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Courses table
CREATE TABLE IF NOT EXISTS "courses" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "title" VARCHAR NOT NULL,
    "language" VARCHAR NOT NULL,
    "level" VARCHAR NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Lessons table
CREATE TABLE IF NOT EXISTS "lessons" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "courseId" UUID NOT NULL REFERENCES "courses"("id") ON DELETE CASCADE,
    "title" VARCHAR NOT NULL,
    "description" TEXT,
    "orderIndex" INTEGER NOT NULL,
    "createdAt" TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Progress table (tracks user lesson completions)
CREATE TABLE IF NOT EXISTS "progress" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "userId" UUID NOT NULL REFERENCES "users"("id") ON DELETE CASCADE,
    "lessonId" UUID NOT NULL REFERENCES "lessons"("id") ON DELETE CASCADE,
    "completed" BOOLEAN DEFAULT FALSE NOT NULL,
    "score" INTEGER DEFAULT 0 NOT NULL,
    "completedAt" TIMESTAMP
);

-- Quizzes table (one per lesson)
CREATE TABLE IF NOT EXISTS "quizzes" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "lessonId" UUID NOT NULL UNIQUE REFERENCES "lessons"("id") ON DELETE CASCADE,
    "title" VARCHAR NOT NULL,
    "passingScore" INTEGER DEFAULT 60 NOT NULL
);

-- Questions table
CREATE TABLE IF NOT EXISTS "questions" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "quizId" UUID NOT NULL REFERENCES "quizzes"("id") ON DELETE CASCADE,
    "text" TEXT NOT NULL,
    "type" VARCHAR DEFAULT 'multiple_choice' NOT NULL,
    "orderIndex" INTEGER DEFAULT 1 NOT NULL
);

-- Answers table
CREATE TABLE IF NOT EXISTS "answers" (
    "id" UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    "questionId" UUID NOT NULL REFERENCES "questions"("id") ON DELETE CASCADE,
    "text" VARCHAR NOT NULL,
    "isCorrect" BOOLEAN DEFAULT FALSE NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS "idx_lessons_courseId" ON "lessons"("courseId");
CREATE INDEX IF NOT EXISTS "idx_lessons_orderIndex" ON "lessons"("courseId", "orderIndex");
CREATE INDEX IF NOT EXISTS "idx_progress_userId" ON "progress"("userId");
CREATE INDEX IF NOT EXISTS "idx_progress_lessonId" ON "progress"("lessonId");
CREATE INDEX IF NOT EXISTS "idx_progress_userId_lessonId" ON "progress"("userId", "lessonId");
CREATE INDEX IF NOT EXISTS "idx_questions_quizId" ON "questions"("quizId");
CREATE INDEX IF NOT EXISTS "idx_answers_questionId" ON "answers"("questionId");
